version: "3.9"
services:
    server:
        build: ./server
        image: new-server
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports: 
        - "8000:8000"
        volumes: 
        - ./server/:/app/server/
        depends_on:
        - "db"
    db:
        image: postgres:13.2-alpine
        environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=meme_tweets
        ports:
        - "5433:5433"
        volumes: 
        - meme-tweets:/var/lib/postgresql/data
volumes: 
    meme-tweets:
